name: GitHub 3D Contrib

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add -A
          git commit -m "Update 3D contributions" || echo "No changes to commit"
          git push
