name: GitHub 3D Contrib

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-3d-contrib
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate 3D Contributions
        uses: jstrieb/github-stats@v3
        with:
          filename: profile-3d-contrib.svg
          username: ${{ github.repository_owner }}
          color_scheme: green
          
      - name: Commit & Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add -A
          git commit -m "Update 3D contributions" || echo "No changes to commit"
          git push
